### PR TITLE
Bump to msys 1.0.18 to get new shellshock-proof bash.

### PR DESCRIPTION
**Pull request by ksubrama**
For #238

### CODE REVIEW

**Comment by XhmikosR** [comment]
You don't need msysCore 1.0.18 for this; updating bash only should work fine too.

**Comment by ksubrama** [comment]
Oh ok.  The source file was named "bash-3.1.23-1-msys-1.0.18" and I didn't know if that somehow signified that it needed msys-1.0.18.  I'll remove the rest and just bump bash ahead.

**Comment by XhmikosR** [comment]
That means it was built against 1.0.18 :P

**Comment by ksubrama** [comment]
@Azolo Hello!  Can we get shell-shock proofing into a ruby release for windows?

**Comment by Azolo** [comment]
Hey @ksubrama thanks for the Pull request. I'm going to go ahead and merge it.

But as for a new DevKit release, not any time soon. Sorry, I've been really busy.

Also, for what we use bash for, running `configure` scripts, I don't see this as being a potential attack vector for a emergency release. But the next release will definitely include this.

**Comment by ksubrama** [comment]
That sounds fine - thanks for the quick response!

**Pull request merged**
