### PR TITLE
generate doc set visibility to private

### PR DESCRIPTION
**Pull request by windwiny**
--visibility=VISIBILITY      Minimum visibility to document a method.
                                 One of 'public', 'protected' (the default),
                                 'private' or 'nodoc' (show everything)

### CODE REVIEW

**Comment by Azolo** [comment]
Hmm, is there a good reason to make `private` methods be shown by default? I'm not necessarily against it if there is a good reason. But..  
I am worried it may confuse new comers, they see a method in the docs then wonder why they can't use it.

**Comment by windwiny** [comment]
I think it should maintain the integrity of the document.

ruby-doc site http://ruby-doc.org/core-2.3.0/Module.html  show `Private Instance Methods` now.
I want chm files become a good alternative when internet offline.

**Comment by windwiny** [comment]
And, I think `rdoc` can't handle `nodoc` and `private method` in same way.

The end-users maybe never need `nodoc` methods;
but maybe want/need to use `private class/instance methods`.

**Comment by Azolo** [comment]
@windwiny Do you think that the `stdlib` should include the `private` methods as well?

**Comment by windwiny** [comment]
@Azolo , i think yes.

`gem` `open` `require` `scanf` .. ,   all is  `stdlib` `Kernel` module's `Private Instance Methods`,
those are very common method, if can not find them's document, that is not good.

**Comment by Azolo** [comment]
Very good argument. I'm convinced.

**Pull request merged**
