### PR TITLE
add ruby version 2.3

### PR DESCRIPTION
**Pull request by windwiny**

### CODE REVIEW

**Comment by Azolo** [comment]
Wow, you're awesome. I'm going to wait on merging this until I get some test data. (if you look at previous version upgrades they come with `make test-all` results)

As soon as I get that I am putting it in the merge information into `master`. Thanks!

**Comment by johnnyshields** [comment]
Any update on this PR?

**Comment by windwiny** [comment]
`make test-all` has many failed, and i don't know how to solve those problem.

**Comment by johnnyshields** [comment]
Can we report all failures to the Ruby bug tracker and try to get them patched in 2.3.1?

**Comment by Azolo** [comment]
@windwiny You can't really solve those problems, we just release it as is since there is already a release out there.

@johnnyshields Honestly, that would be awesome. I am super bad about reporting those bugs, mainly because I only catch them after a release which is too late for a fix for that release.

**Comment by johnnyshields** [comment]
@Azolo the same situation has happened with every yearly Ruby release (2.0, 2.1, 2.2, and now 2.3.) :(

@windwiny can you please post the log of failing cases to Ruby core tracker?

**Comment by johnnyshields** [comment]
Next steps:
1) Someone to checkout PR #305, run the windows build, and document the failing cases
2) Report the failing cases to the Ruby core team bug tracker

Who can do this?

**Comment by daniel-rikowski** [comment]
I can't complete the build. When compiling the `win32ole` extension I get an error: 

```
make[2]: Entering directory `/c/rubyinstaller/sandbox/ruby23_build/ext/win32ole'
compiling ../../../ruby_2_3/ext/win32ole/win32ole.c
../../../ruby_2_3/ext/win32ole/win32ole.c: In function 'ole_variant2val':
../../../ruby_2_3/ext/win32ole/win32ole.c:1442:17: warning: implicit declaration of function 'V_RECORDINFO'
../../../ruby_2_3/ext/win32ole/win32ole.c:1442:17: error: lvalue required as unary '&' operand
../../../ruby_2_3/ext/win32ole/win32ole.c:1450:21: warning: implicit declaration of function 'V_RECORD'
../../../ruby_2_3/ext/win32ole/win32ole.c:1450:21: error: lvalue required as unary '&' operand
../../../ruby_2_3/ext/win32ole/win32ole.c:1648:28: warning: initialization makes pointer from integer without a cast
../../../ruby_2_3/ext/win32ole/win32ole.c:1649:22: warning: initialization makes pointer from integer without a cast
../../../ruby_2_3/ext/win32ole/win32ole.c: In function 'ole_invoke':
../../../ruby_2_3/ext/win32ole/win32ole.c:2755:17: warning: passing argument 2 of 'olerecord_set_ivar' makes pointer from integer without a cast
../../../ruby_2_3/ext/win32ole/win32ole_record.h:6:6: note: expected 'struct IRecordInfo *' but argument is of type 'int'
../../../ruby_2_3/ext/win32ole/win32ole.c:2755:17: warning: passing argument 3 of 'olerecord_set_ivar' makes pointer from integer without a cast
../../../ruby_2_3/ext/win32ole/win32ole_record.h:6:6: note: expected 'void *' but argument is of type 'int'
make[2]: *** [win32ole.o] Error 1
make[2]: Leaving directory `/c/rubyinstaller/sandbox/ruby23_build/ext/win32ole'
```

What can I do to fix this? Or is this one of the expected errors which need to be fixed by the Ruby core team?

**Comment by windwiny** [comment]
Sorry, i'm late.
I had reported the failing cases logfiles to https://bugs.ruby-lang.org/issues/12193

**Comment by daniel-rikowski** [comment]
Jugding from the log files you had no problem compiling the win32ole extension. Any idea on what might be the problem on my workstation?

**Comment by espinosa** [comment]
I try to compile the last 2.3.0 p7 version using the rake option CHECKOUT=1 but have a SSL certificate error. Has someone the same error ? I think is better to take the last version released on february instead of the first version released on december.

**Comment by windwiny** [comment]
@daniel-rikowski  Which is you OS version? 
Maybe you have other version gcc, you may check environment like PATH, INCLUDE, LIB  etc ..

**Comment by windwiny** [comment]
@espinosa  Did you `SSL certificate error` mean like this

    downloading config.guess ... downloader.rb:172:in `rescue in download': failed to download config.guess (RuntimeError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed: https://raw.githubusercontent.com/gcc-mirror/gcc/master/config.guess

you can download http://curl.haxx.se/ca/cacert.pem , and 

    set SSL_CERT_FILE=c:\cacert.pem

**Comment by windwiny** [comment]
Good news, guys
Now 2.3.0p0 and 2.3.0p7 `make test-all` has 2 failed only.

**Comment by shirosaki** [comment]
I've submitted a patch to fix rubygems temp path issue.
https://github.com/rubygems/rubygems/pull/1554

**Comment by espinosa** [comment]
Thanks @windwiny, that's resolved the problem with the certificate...
Now I have between 37 and 42 failures depending on which console I use to run the test.
I use Windows 7. Exemple:
Test_Win32Console#test_reverse_bold <240> expected but was <15>.

**Comment by daniel-rikowski** [comment]
I tried originally tried it on Windows 10 with Ruby 2.2.4 installed. 
After your suggestion I tried a fresh install of Windows 7 with Ruby 2.2.4. Same error though. 

PATH does not contain any GCC compiler and the other variables were not set.

**Comment by windwiny** [comment]
@daniel-rikowski 
The `rubyinstaller` working directory clean,  and merged this repo master branch all commit ?  latest commit is `4070b5c`.  
and delete or rename `sandbox` directory. rake task will re-create devkit and unpack source files.

**Comment by daniel-rikowski** [comment]
@windwiny That was the problem: A rookie mistake on my part.

I just checked out *your* repository and switched to the ruby23 branch.
After checking out *this* repo and then merging your branch it worked.

Thank you for figuring this out!

**Comment by johnnyshields** [comment]
@shirosaki thanks for your patch, looks like it's merged now.

@windwiny how many failures on latest Ruby master?

**Comment by windwiny** [comment]
@johnnyshields  ruby_2_3 branch still keep patch 7,  compile and test it on 2008 x64, has 1 failed and 1 error.

    [ 4311/15555] TestFile#test_file_share_delete = 0.02 s
      1) Failure:
    TestFile#test_file_share_delete [d:/ruby_git/test/ruby/test_file.rb:418]:
    Exception raised:
    <#<Errno::EACCES: Permission denied @ unlink_internal - c:/temp/test_file_share_delete20160318-3724-vlbub9/x>>.

    Leaked tempfile: TestGemExtBuilder#test_build_extensions_extconf_bad: #<Tempfile:./siteconf20160318-3724-fpjtyb.rb (clos
    ed)>
    Leaked tempfile: TestGemExtExtConfBuilder#test_class_build_env_make: #<Tempfile:./siteconf20160318-3724-vh1pi9.rb (close
    d)>
    Leaked tempfile: TestGemExtExtConfBuilder#test_class_build_extconf_fail: #<Tempfile:./siteconf20160318-3724-1v36svk.rb (
    closed)>
    [ 7581/15555] TestIO#test_write_32bit_boundary = 47.66 s
      2) Error:
    TestIO#test_write_32bit_boundary:
    ArgumentError: marshal data too short
        d:/ruby_git/test/lib/test/unit/assertions.rb:604:in `load'
        d:/ruby_git/test/lib/test/unit/assertions.rb:604:in `assert_separately'
        d:/ruby_git/test/ruby/test_io.rb:3139:in `block in test_write_32bit_boundary'
        d:/ruby_git/test/ruby/test_io.rb:1499:in `make_tempfile'
        d:/ruby_git/test/ruby/test_io.rb:3120:in `test_write_32bit_boundary'

    Finished tests in 977.862725s, 15.9031 tests/s, 2267.8551 assertions/s.
    15551 tests, 2217651 assertions, 1 failures, 1 errors, 164 skips

    ruby -v: ruby 2.3.0p7 (2016-02-23 revision 53898) [i386-mingw32]
    make: *** [yes-test-all] Error 2

**Pull request merged**
