### PR TITLE
Use msys2(32bit) instead of old msys

### PR DESCRIPTION
**Pull request by shirosaki**
I've changed to use msys2 for ruby build so that parallel make works without hang.
Old msys has a bug of  parallel make.

Parallel make hangs due to msys bug.
http://sourceforge.net/p/mingw/bugs/1950/

msys2 is updated version of msys and the bug seems to be fixed.
http://mingw-users.1079350.n2.nabble.com/Status-of-MSYS2-td7582391.html

### CODE REVIEW

**Comment by shirosaki** [comment]
I rebased and updated msys2 packages.
Ruby build works fine. I tested trunk with mingw64-64.4.7.2.
msys is not actively maintained now. I think msys2 is better for build environment.

**Comment by shirosaki** [comment]
@Azolo this pull request don't include gcc update. Only msys and other tools replacement.
I think we can update the following devkit to mingw64 gcc 4.7.2 with msys2.
DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe and 
DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe.

**Comment by Azolo** [comment]
@shirosaki Alright, let me finish up with Ruby 2.3 and the Holidays and I'll merge it. I want to update mingw and the DevKit in general for 2.4 anyway. (See #297)

**Comment by johnnyshields** [comment]
I think this can be closed as @larskanis branch will fix it.

**Pull request closed without merging**
